"""Empty Init

Revision ID: 531e6ecb0375
Revises: 
Create Date: 2023-06-05 14:29:00.163955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531e6ecb0375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
